### Shape 변환 연습: 7월 25일까지
아래의 변환을 numpy array 데이터에서 연습해보세요.

#### [순서 바꾸기]
    (100, 3, 256, 256) <-> (100, 256, 256, 3)

In [46]:
import numpy as np
import copy

In [66]:
# 1. 인덱스로 순서 바꾸기 1

arr = np.array((100, 3, 256, 256))
carr = copy.deepcopy(arr)

arr[3] = carr[1]
arr[1] = carr[3]

arr

array([100, 256, 256,   3])

In [67]:
# 2. 인덱스로 자리 바꾸기 2

arr = np.array((100, 3, 256, 256))

arr[3] = arr[1]
arr[1] = arr[2]

arr

array([100, 256, 256,   3])

In [68]:
# 3. 값 직접 대입

arr = np.array((100, 3, 256, 256))

arr[1] = 256
arr[3] = 3

arr

array([100, 256, 256,   3])

#### [차원 늘리기/줄이기]
    (100, 100) -> (1, 100, 100) / (100, 1, 100) / (100, 100, 1) -> (100, 100)

In [103]:
# 1. insert & delete 원하는 인덱스에 추가할 값 입력

arr = np.array((100, 100))

arr1 = np.insert(arr, 0, 1)
arr2 = np.insert(arr, 1, 1)
arr3 = np.insert(arr, 2, 1)
arr4 = np.delete(arr3, 2)

print(arr, arr1, arr2, arr3, arr4, sep="\n")


[100 100]
[  1 100 100]
[100   1 100]
[100 100   1]
[100 100]


In [119]:
# 2. insert & delete 원하는 인덱스에 추가할 값 입력

arr = np.array((100, 100))
print(arr)

for i in range(3):
    arr = np.insert(arr, i, 1)
    print(arr)    
    arr = np.delete(arr, i)

print(arr)

[100 100]
[  1 100 100]
[100   1 100]
[100 100   1]
[100 100]


#### [데이터 나누기]
    (100, 3, 256, 256) -> (100, 1, 256, 256), (100, 1, 256, 256), (100, 1, 256, 256)
    (100, 3, 256, 256) -> (100, 3, 256, 128), (100, 3, 256, 128)

In [192]:
# 1. 이렇게 하는 것이 맞나?

arr = np.array((100, 3, 256, 256))
carr = np.array((100, int(arr[1]/arr[1]), 256, 256))

for i in range(arr[1]+1):
    arr = np.array([carr]*i) # arr[1]의 값만큼 배열 추가
    
arr

array([[100,   1, 256, 256],
       [100,   1, 256, 256],
       [100,   1, 256, 256]])

In [213]:
# 2. 이렇게 하는 것이 맞나?

arr = np.array((100, 3, 256, 256))
carr = np.array((100, int(arr[1]/arr[1]), 256, 256))
arr_list = []

for i in range(arr[1]):
    arr_list.append(np.array([carr]))
    
print(arr_list)

[array([[100,   1, 256, 256]]), array([[100,   1, 256, 256]]), array([[100,   1, 256, 256]])]


In [186]:
# 3. 이렇게 하는 것이 맞나?

div_num = 2
arr = np.array((100, 3, 256, 256))
carr = np.array((100, 3, 256, int(arr[3]/div_num)))

for i in range(div_num+1):
    arr = np.array([carr]*i) # div_num의 값만큼 배열 추가
    
arr

array([[100,   3, 256, 128],
       [100,   3, 256, 128]])

In [214]:
# 3. 이렇게 하는 것이 맞나?

div_num = 2
arr = np.array((100, 3, 256, 256))
carr = np.array((100, 3, 256, int(arr[3]/div_num)))

for i in range(div_num+1):
    arr = np.array([carr]*i) # div_num의 값만큼 배열 추가
    
arr

array([[100,   3, 256, 128],
       [100,   3, 256, 128]])

In [225]:
# 3. 이렇게 하는 것이 맞나?

div_num = 2
arr = np.array((100, 3, 256, 256))
carr = np.array((100, 3, 256, int(arr[3]/div_num)))
arr_list = []

for i in range(div_num):
    arr_list.append(np.array([carr]))
    
arr_list

[array([[100,   3, 256, 128]]), array([[100,   3, 256, 128]])]

#### [데이터 합치기] 
    (100, 3, 256, 256), (100, 3, 256, 256) -> (100, 6, 256, 256)
    (100, 3, 256, 256), (100, 3, 256, 256) -> (200, 3, 256, 256)
    (100, 3, 256, 256), (100, 3, 256, 256) -> (100, 3, 256, 512)

In [235]:
# 1. 이렇게 하는 것이 맞나?

arr1 = np.array((100, 3, 256, 256))

arr2 = np.array((100, arr1[1]+arr1[1], 256, 256))
arr3 = np.array((arr1[0]+arr1[0], 3, 256, 256))
arr4 = np.array((100, 3, 256, arr1[3]+arr1[3]))

print(arr2, arr3, arr4, sep="\n")

[100   6 256 256]
[200   3 256 256]
[100   3 256 512]


#### [평균값 구하기] 
    (100, 50, 30) -> (100, 50)
    (100, 50, 30) -> (100, 30)
    (100, 50, 30) -> (100)
    (100, 50, 30) -> 값

In [ ]:
# 모르겠다...

#### [max / min 값만 뽑아서 새로운 데이터 만들기]
    (100, 50, 30) -> (100, 50)
    (100, 50, 30) -> (100, 30)
    (100, 50, 30) -> (100)
    (100, 50, 30) -> 값 

In [ ]:
# 모르겠다...